### ISSUE TITLE
Add UNFCCC - IFI as a provider of annual country carbon intensity emissions figures

### ISSUE THREAD

**Issue by mrchrisadams** [thegreenwebfoundation/grid-intensity-go#8]
I've been looking around, and it looks like there's a helpful set of annual emissions factors for countries that have been commissioned and created by the [United Nations International Financial Institutions project](https://unfccc.int/climate-action/sectoral-engagement/ifis-harmonization-of-standards-for-ghg-accounting).

### TODO

_this is the TLDR for this issue_

- [ ] Add default global figure for 2021 (if we have this as a fall back we can at least implement most of the code itself )
- [x] clarify license and of the figures in the spreadsheet (can we include them in an Apache 2 licensed codebase? Are we able to relicense this data for use in OSS projects?)
- [x] create test harness, to flesh out the API following with the same [same Provider Interface as the other providers](https://github.com/thegreenwebfoundation/grid-intensity-go/blob/main/provider.go#L7-L9)
- [x] implement IFI Provider, and check about the correct name.

In particular, there's section about why they were created in the first place on the project, and I think it's worth sharing here:

> ### Stakeholders' expectations
>
> Donors as well as institutional investors expect standards that are simple to use but that also ensure comparability of GHG emissions estimates to inform their decision-making related to project finance. They also expect the standards to be credible, transparent and widely accepted.
>
![expectations](https://user-images.githubusercontent.com/17906/154918584-aef35327-39f4-47f7-a4cb-64bcd6f91930.png)

These provide:

- a) recent figures for every single country in the UN (although without the corresponding ISO two or three letter codes. These can be added into a Golang `map` or json file to read).
- b) guidance on how to use these in various contexts as they provide.

I understand the intention of these to be widely available, providing _some_ kind of sensible baseline for discussions about carbon emissions from activity. I can't see how you'd do this without the information being open, because if the information isn't open, then only the people who can afford the data get to make any data-informed arguments.

That seems to go against the stakeholder expectations, although this is a thing we'd need to confirm though, obvs.

### A sample of the data

Here's the [link to the data in the spreadsheet - Harmonized IFI Default Grid Factors 2021 v3.1](https://unfccc.int/sites/default/files/resource/IFI%20Default%20Grid%20Factors%202021%20v3.1_unfccc.xlsx)

The first four numerical numbers are combined margin emission factors - as I understand it, this looks like it factors in future deployment, which is in most cases expected to be lower carbon than the existing infra.

Country / Territory / Island | Firm Energy (e.g., Hydro, Geothermal)  | Intermittent Energy (e.g., Solar, Wind, Tidal)| Energy Efficiency   |  Electricity Consumption |  Operating Margin Grid Emission Factor, gCO2/kWh (including for use in PCAF GHG accounting) 
-- | -- | -- | -- | -- | --
Afghanistan | 193 | 331 | 193 | 193 | 414
Albania | 0 | 0 | 0 | 0 | 0
Algeria | 397 | 479 | 397 | 397 | 528
American Samoa (U.S.) | 516 | 664 | 516 | 516 | 753
Andorra | 70 | 144 | 70 | 70 | 188
Angola | 748 | 1203 | 748 | 748 | 1476

### What the columns mean

> The common dataset containing DEFs is constructed using a Combined Margin (CM) for the grid that is comprised of an Operating Margin (OM) and a Build Margin (BM). The OM and BM are terms defined under the clean development mechanism (CDM)2 for grid connected electricity generation from renewable sources:
>
> (a) The OM represents the cohort of existing power plants whose operation will be most affected (reduced) by the project;
> (b) The BM represents the cohort of the prospective/future power plants whose construction and operation could be affected by the renewable energy project, based on an assessment of planned and expected new generation capacity.

So, in other words:

1. the OM is a figure for energy from existing power plants - i.e. this is how much is carbon is produced for every kilowatt hour of electricity at present. These come from a range of different places, and it's not clear what the licensing is for this information.
2. The BM is for future generation that _might or might not get built_. i.e. if you have a nice geothermal plant providing 2GW of clean, firm power, then perhaps you don't need to generate 2GW from that planned coal plant after all. We're not sure if these will be built though, so we calculate them separately, as it doesn't make sense to try factoring either into the emissions at present.

The first four columns with numbers are _combined margin_ grid emission factors. These are different to the OM ones, as you can see.

As I mentioned before, I think the OM figures are higher because they're not trying to incorporate future planned infrastructure - you might care about this if you were making an investment with a 10-20 year time horizon (i.e. do I build this solar farm?), but it's less relevant for understanding the carbon footprint of electricity today.

### Guidance on their use

There is some guidance on where you would use these country level figures from [Methodological Approach for the Common Default Grid Emission Factor Dataset - AHG 001](https://unfccc.int/sites/default/files/resource/IFITWG_Methodological_approach_to_common_dataset.pdf):

> This approach is most appropriate to apply in the case where grid emissions associated with project electricity consumption cannot be estimated accurately (e.g., due to paucity of hourly generation profile data or estimation of such would require sophisticated modelling). A tier 1 approach cannot be used with projects that actively manage electricity loads by modifying consumption profiles to achieve desired goals (e.g., matching consumption with the availability of electricity produced from a specific energy source).

Tier 1 here basically means _default_ energy figures at country level, when you have no other info available. It's one step better than a global estimate i.e. 440g CO2/KWh. 

Tier 2 and tier 3 refer to higher resolution, like grid or even grid region level, where you _do_ have information where the number might be different where the generation is in a country, and when it's being run. This might be the case if you had access to one of the other APIs we have support for.

For the purposes of understanding your emissions from compute you use _now_, where you aren't doing anything clever like moving compute loads through time or space in response to the grid itself changing, the OM figures look like they would work as a baseline.

Here's some quoted guidance their usage as outlined in [Methodology/approach to account project emissions associated with grid electricity consumption - AHG-002](https://unfccc.int/climate-action/sectoral-engagement/ifis-harmonization-of-standards-for-ghg-accounting/ifi-twg-list-of-methodologies)

Emphasis is mine:

> This guidance applies to any investment project that uses grid electricity as an energy source. Examples of project types that are relevant for the approach are provided below (the list below is not exhaustive).
> (a) Heat pumps, lights and appliances in buildings;
> (b) Electric motors, pumps, robots, etc. in manufacturing facilities;
> (c) Pumps, sensors and control systems in waste-water treatment plants;
> **(d) Servers, telecommunications towers, computers, telephones and other ICT devices;**
> (e) Electric vehicles (buses, cars, trucks, lawn motors, forklifts at ports, and tractors in agriculture, etc.).

This makes me think they would work as a useful default set of numbers for the countries, to use for calculating emissions from an infra set up at present - _a baseline of sorts_.

### Comparing these to higher time resolution marginal emissions numbers from APIs

I don't think this is the same as the data from marginal computing APIs, but I'll readily admit that even now, I'm not sure.

I understood marginal intensity from API s on a short time horizon was for people figuring out _right now_ for example, whether turning something on or off would have much of an affect on the carbon intensity on the grid. 

If you wanted to work out the carbon savings from clever scheduling of compute you might compare these numbers with a marginal API, like that provided by [Wattime](https://nextjournal.com/greenweb/experiments-with-the-free-marginal-carbon-intensity-from-wattime), [Electricity Map's Marginal API](https://electricitymap.org/blog/marginal-carbon-intensity-of-electricity-with-machine-learning/), the [Carbon intensity in the UK provided by the National Grid](https://carbonintensity.org.uk/), and so on.

These APIs give you some idea of what each marginal unit of usage might be - so rather than _looking at the whole fleet of power plants, and allocating a share to you that's the same as the energy your server is using_, they're looking at the ones that would need to be switched on based on their current view of the conditions on the entire grid, _as a consequence of you running that compute, and causing the extra demand for electricity to power that server_.

These aren't the same, and they tend to be higher, as you'd typically switch on faster responding fossil fuel generation to meet this need.

These seem conceptually similar to the marginal figures in the dataset linked above, but after reading the guidance, I get the impression that the annual, by-country figures in the dataset are more about deciding whether to finance a whole new energy project, rather than deciding if existing, often dirtier capacity should be spun up to meet an uptick in demand.

It may be the case that these balance out anyway over the long term, but I'm leaving a note here, for discussion, and to ask others for pointers,

**Comment by mrchrisadams** [comment]
I've been chatting with other people on the GSF SCI data project, and based on that discussion I'll see if it's realistic to have an annual, marginal figure as a simplified fallback.

You can see more about that project below:

https://github.com/Green-Software-Foundation/sci-data/

If that doesn't work, I've found out that the dataset compiled by Ember is Creative commons Sharealike Attribution:

https://ember-climate.org/global-electricity-review-2021/data-explorer/

This would allow us to include by-country figures, but the difference is that I think these figures would **not** be marginal figures in the same sense as the dataset described here.

I've arranged a call to speak to them to ask a few more questions, because for many cases, having the non-marginal figures would still be useful for attributional use-cases, like annual reporting, or plugging into tools like cloud carbon footprint.

I'll add further notes about the Ember dataset, but I imagine the implementation would be almost the same as this one here - simply doing a key value lookup by country and perhaps year #11

**Comment by mrchrisadams** [comment]
Good news! we have the green light to publish and use this data!

I've outlined a few steps we might want to take in co2.j2#97, to prepare it for use.

https://github.com/thegreenwebfoundation/co2.js/issues/97

I'm not sure where it makes sense to put this data for use, but this means we have another provider we can add, that also provides the marginal intensity numbers that make it possible to use in SCI measurements.
